#
#  Chinese National Engineering Research Centre for Steel Structure
#  (Hong Kong Branch)
#
#  Hong Kong Polytechnic University
#
#  Author: Victor W H Wu
#  Date: 22 August, 2023.
#
joint_names: 
  [shoulder_pan_joint, 
   shoulder_lift_joint, 
   elbow_joint, 
   wrist_1_joint, 
   wrist_2_joint, 
   wrist_3_joint
  ] 
